### ISSUE TITLE
Veralteter Transportalgorithmus | web.de Voreinstellung fehlerhaft

### ISSUE THREAD

**Issue by DcFamas** [iobroker-community-adapters/ioBroker.email#111]
Hallo zusammen,
ich wollte gerne meinen web.de Account für den E-Mail Versand von ioBroker nutzen.
Das System ist auf dem aktuellesten Stand mit Admin v.5.

Generell ist die Voreinstellung von web.de fehlerhaft. Ich denke da hier ggf. noch direkt Port 25 SMTP genutzt werden möchte, lehnt web.de die Verbindung ab.

Aufgrunddessen wollte ich die Einstellung selbstständig, wie in meiner FRITZ!Box vornehmen:

![grafik](https://user-images.githubusercontent.com/35306967/130959638-1e03f5f4-bb04-46ce-9b13-0864fcf289b2.png)

Es erscheint folgende Fehlermeldung:

`Fehler 140003732326272:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: `

Da SSL mittlerweile out-of-support ist, gehe ich davon aus, dass hier der Algorithmus der benutzt wird angepasst werden muss, oder?

Danke! :)

**Comment by Monox83** [comment]
Problem besteht noch immer…

**Comment by Apollon77** [comment]
Please check GitHub version. Does it work there?

**Comment by DcFamas** [comment]
Ich erhalte Fehlermeldung:
Fehler 535 Authentication credentials invalid

"Benutzer" wurde jeweils mit und ohne Domäne versucht. Kennwort ist definitiv richtig und wurde via. Web-Anmeldung und FRITZ!Box verifziert.

**Comment by Apollon77** [comment]
bitte mal Custom Einstellungen versuchen und ggf so einrichten wie es web.de verlangt ... geht es dqnn? Wenn ja bitte Einstellungen posten

**Comment by DcFamas** [comment]
Es erscheint leider derselbe Fehler:
Fehler 139974949832576:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

**Comment by DcFamas** [comment]
Muss zurückrudern, web.de hatte den POP3/IMAP Abruf deaktiviert. Die Fehlermeldung war also korrekt, alles gut. Die Voreinstellung "web.de" ist richtig und funktioniert. Danke für deine schnelle Hilfe!
