### ISSUE TITLE
1und1 is IONOS

### ISSUE THREAD

**Issue by Dtrieb** [iobroker-community-adapters/ioBroker.email#160]
1und1 change the name to ionos.

<html>
<body>
<section id="c179972" class="secondary" style="border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: OpenSansRegular, Arial, &quot;Arial Narrow&quot;, sans-serif; margin: 0px; padding: 28px 0px; vertical-align: baseline; display: block; background-color: rgb(248, 248, 248); position: relative; color: rgb(80, 87, 91); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sheet-block" style="border: 0px; font: inherit; margin: 0px; padding: 0px 30px; vertical-align: baseline;"><h3 class="subheadline-section" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 19px; line-height: 1.3333em; font-family: OverpassBold, Arial, sans-serif; margin: 0px 0px 12px; padding: 0px; vertical-align: baseline; color: rgb(31, 40, 45); -webkit-font-smoothing: antialiased;">Verbindungsdaten für IONOS Mailserver</h3>

KONTOTYP | IMAP | POP3
-- | -- | --
Server | imap.ionos.de | pop.ionos.de
Port | 993 | 995
Verbindungstyp / Verschlüsselung | SSL/TLS | SSL/TLS

</div></section>
</body>
</html>Verbindungsdaten für IONOS Mailserver
Posteinganggserver (IMAP, POP3)
KONTOTYP	IMAP	POP3
Server	imap.ionos.de	pop.ionos.de
Port	993	995
Verbindungstyp / Verschlüsselung	SSL/TLS	SSL/TLS
Postausgangsserver (SMTP)
 	 
Server	smtp.ionos.de
Port	465
Verbindungstyp	SSL/TLS
Freie Wahl des Kontotyps
Wenn Sie ein E-Mail-Konto in Ihrem E-Mail-Programm einrichten, können Sie in der Regel zwischen den Kontotypen IMAP und POP3 wählen. Beides sind Methoden des E-Mail-Empfangs von einem Mailserver. Sie unterscheiden sich jedoch darin, wie Sie Ihren E-Mail-Bestand verwalten. Eine Erläuterung und Gegenüberstellung der beiden Methoden finden Sie im Artikel [Unterschiede zwischen IMAP und POP3](https://www.ionos.de/hilfe/e-mail/allgemeine-themen/unterschiede-zwischen-imap-und-pop3/).

Wir empfehlen allgemein, IMAP zu verwenden. Geben Sie dazu einfach imap.ionos.de als Posteingangsserver und die Nummer 993 für den Server-Port in Ihrem E-Mail-Programm ein.

Anmeldeinformationen für IONOS Mailserver
Um E-Mails senden und empfangen zu können, ist eine Authentifizierung auf dem Mailserver von IONOS erforderlich. Daher müssen Sie bei der Einrichtung des E-Mail-Programms zusätzlich zu den Verbindungsdaten auch den Benutzernamenund das Passwort Ihres E-Mail-Kontos eingeben.

EINSTELLUNG	IHRE EINGABE
Benutzername	Ihre vollständige E-Mail-Adresse.
Beispiel: mustermann@ionos.de
Passwort	Das Passwort zu Ihrer E-Mail-Adresse bzw. Ihrem E-Mail-Postfach.

Quelle: [https://www.ionos.de/hilfe/e-mail/allgemeine-themen/serverinformationen-fuer-imap-pop-und-smtp/](https://www.ionos.de/hilfe/e-mail/allgemeine-themen/serverinformationen-fuer-imap-pop-und-smtp/)

**Comment by Apollon77** [comment]
Can you please check out the GitHub version? 1und1 should now use the ionos server (and new entry ionos is also available)
