### ISSUE TITLE
Fehlermeldung bei Instanzeinstellungen für mail.ee

### ISSUE THREAD

**Issue by MichaelSchaaf999** [iobroker-community-adapters/ioBroker.email#173]
**Describe the bug**  

Fehler Hostname/IP does not match certificate's altnames: Host: smtp.mail.ee. is not in the cert's altnames: DNS:mail.inbox.eu, DNS:mail.ee, DNS:mail.inbox.la, DNS:mail.inbox.lt

**Expected behavior**  
Sending an eMail from the iOBroker Mail-Adapter without errors.

**Screenshots & Logfiles**  

<img width="821" alt="image" src="https://user-images.githubusercontent.com/53481090/167691704-f8266efa-1d80-47b2-b410-99e7407f07b9.png">

**Versions:**  
 - Adapter version: <adapter-version> 1.0.10
 - JS-Controller version: <js-controller-version>   4.0.21
 - Node version: <node-version>   v 14.19.0
 - Operating system: <os-name>  Debian

**Additional context**  
-

**Comment by Apollon77** [comment]
But the error message should be clear or? The provided SL certificate do not include the used domainname.

Can you please provide the infos on the mail server configuration for mail.ee?

Ther emight be a setting to ignore SSL errors in the adapter. did you tried that?

**Comment by MichaelSchaaf999** [comment]
Error message is clear, yes. But no idea how to handel this.


Are you talking about this configuration?

If you are using the POP3 protocol:

 

POP3 (incoming mail server): mail.ee

    Encryption: Must be turned on SSL
    Port POP3: 995

SMTP (outgoing mail server): mail.ee

    Encryption: Must be turned on TLS vai SSL
    Ports SMTP: 587 (in case if you use TLS)
    Ports SMTP: 465 (in case if you use SSL)

If you are using the IMAP protocol:

 

IMAP (incoming mail server): mail.ee

    Encryption: Must be turned on SSL
    Ports IMAP: 993

SMTP (outgoing mail server): mail.ee

    Encryption: Must be turned on TLS or SSL
    Ports SMTP: 587 (in case if you use TLS)
    Ports SMTP: 465 (in case if you use SSL)

​The service has been enabled:
![grafik](https://user-images.githubusercontent.com/53481090/168230808-a6b7e97d-6ddf-4f87-acba-ccf599f4f442.png)


There is no setting to ignore SSL errors.

**Comment by Apollon77** [comment]
Ok, here we have it ... seems they changed the domainname for smtp. Can you choose custom please and setup according to above and see if it works that way and post the needed custom settings? Then I change it

**Comment by MichaelSchaaf999** [comment]
<img width="612" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168244333-2c1a0b9a-669d-4d27-a331-e7c1e2b0329c.png">


Result:

<img width="383" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168244405-cde01b65-45d6-4462-9750-cde4d797e902.png">

wott?

**Comment by Apollon77** [comment]
Nimm mal 587 als Port bitte

**Comment by MichaelSchaaf999** [comment]
done.

<img width="566" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168249686-e671ae3c-6ea3-4c56-ad4f-051c1613bb87.png">


<img width="342" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168249753-ea727d3d-6af6-494a-899c-bbf6af5507ae.png">

**Comment by MichaelSchaaf999** [comment]
ah, Moment, die nehmen ein spezielles PW beim SMTP Versand

![grafik](https://user-images.githubusercontent.com/53481090/168250989-f4848bee-cd71-4a62-ad7b-7b250101ad3a.png)

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168251103-3c171abf-e034-4f52-99c1-80365b90bbc2.png">


<img width="266" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168251152-9ab9150e-5ace-4c16-a78d-2fa79468b6e8.png">

<img width="1182" alt="grafik" src="https://user-images.githubusercontent.com/53481090/168251254-d97f5436-bf05-4da2-ac98-d1eb98179c94.png">


Mail kam an.

**Comment by Apollon77** [comment]
Alles klar, dann fixe ich die Tage mal die Default Settings

**Comment by MichaelSchaaf999** [comment]
Danke Dir für die Mühe & Deine Zeit!

**Comment by Apollon77** [comment]
In v1.1.2 sollte nun auch die Auswahl von mail.ee wieder ohne Custom tun

**Comment by MichaelSchaaf999** [comment]
<img width="311" alt="grafik" src="https://user-images.githubusercontent.com/53481090/169087397-f4baa927-f780-4a1b-8d2f-0b0ddd6f7ab9.png">
Richtige Version?

Führt zu:

<img width="872" alt="grafik" src="https://user-images.githubusercontent.com/53481090/169087547-0e18cd13-4e8d-4288-904a-f99049c6d280.png">

**Comment by Apollon77** [comment]
Nope, wie geschrieben 1.1.2 ... ist ggf morgen spätestens im beta Repo - oder per Admin - Adapter - expertenmodus aktivieren - custom install/GitHub icon - erster Tab "von npm" installieren

**Comment by MichaelSchaaf999** [comment]
Heute installiert: Funzt!
Prima & danke für die Mühe!
