### ISSUE TITLE
STARTTLS at userdefined SMTP configuration not working

### ISSUE THREAD

**Issue by kuckuckmann** [iobroker-community-adapters/ioBroker.email#175]
Using version 1.1.2 & 1.1.1_
Problem: SMTP connection which requires STARTTLS is no longer working

When using user defined SMTP configuration there is no option to configure STARTTLS.
While downloading the `system.adapter.email.0.json` file I can see, that the option `"requireTLS":false`, is set, which is not working.
After Rolling back to version 1.1.0 it's working again.

**Comment by spaceduck518** [comment]
I can confirm this issue!

**Comment by Apollon77** [comment]
In 1.1.x there is a new checkbox "Always use STARTTLS:" ... how you set that? Please show screenshot of you confog

**Comment by Apollon77** [comment]
Ahhh I see .. the checkbox is hidden ... grmmpff... Can you please try GitHub version?

**Comment by kuckuckmann** [comment]
Well, I can see the checkbox now.
Test was successful

**Comment by Apollon77** [comment]
fixed in 1.1.3
