### ISSUE TITLE
emailadapter  iobroker funktioniert nicht mit ionos

### ISSUE THREAD

**Issue by wschiro** [iobroker-community-adapters/ioBroker.email#179]
*habe die letzte Version erfolgreich installiert. die Testmail wird auch abgesendet ohne jegliche Fehlermeldung, aber es kommt nichts an. Der emailaccount bei ionos funktioniert mit anderen emailclients normal.
Adapterversion : 1.1.3
Js-Controller: 4.0.23
nodeversion: 16.5.1
OS: rasberrypi 4

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by wschiro** [comment]
[Protemail.pdf](https://github.com/iobroker-community-adapters/ioBroker.email/files/8998461/Protemail.pdf)

**Comment by Apollon77** [comment]
Und wie sehen die Settings im Adapter aus dwenn Du sie mit den IMAP settings in deinem mail Programm wo es tut vergleichst?

**Comment by wschiro** [comment]
im Adapter ist doch nur smtp und ionos auswählbar, da finde ich kein imap
Die Einstellungen bei ionos sind:
smtp.ionos .de  port 587  erfordert autentifizierung
imap.ionos.de port 993

**Comment by Apollon77** [comment]
Sorry ich meinte die smtp settings, sobst versuch mal die Settings auf "Custom" zu stellen und stelle alles ein Wie es nötig ist und sende mit die mit denen es tut, dann kann ich die ionos defaults vergleichen

**Comment by wschiro** [comment]
hatte ich schon in der alten Adapterversion, da gabs ionos noch nicht.
wenn ich Server und Port verwende, steht im Protokoll 250 Ok, auch wenn ich es mit STARTTLS mache.
Normalerweise kommt ja ein non-delivery report zurück, wenn die email nicht zustellbar ist,  aber der Adapter kann den ja nicht empfangen.
Was wird den mit 250 OK genau bestätigt?

**Comment by Apollon77** [comment]
ja das kanns schon gewesen sein das ionos nur dann sendet wenn absender passt

**Comment by wschiro** [comment]
nur zu meinem Verständnis, ich dachte der adapter macht eine smtp-session. das er sich dabei beim empfänger beglaubigen muss, ist klar, aber mit user/passwd, nicht mit der empfängeradresse. wenn ich dann an eine gmail-adresse schreibe, müsste die Sendung dann ja im ionos-account  unter gesendet zu finden sein. Ist aber nicht, würde mich auch wundern.
die smtp-session ist (war) relativ einfach, konnte man früher von der kommandozeile machen. vor 20 Jahre haben wir sowas gemacht.

**Comment by Apollon77** [comment]
Nein ionos checkt sehr struckt und erlaubt nur emails versenden mit der richtigen absenderadresse und nicht beliebigen absendeadressen soweit ich weiss. Aber das ist eine Frage für die ionos Doku
