### ISSUE TITLE
Mails are not send due to "authentification failed"

### ISSUE THREAD

**Issue by Sneak-L8** [iobroker-community-adapters/ioBroker.email#184]
**Describe the bug**  
After some time I'm getting errors: 
<html><body>

email.0 | 2022-08-10 10:01:02.369 | error | (COMPACT) Error 535 5.7.8 Error: authentication failed:

</body>
</html>

When entering settings and pressing button "Test mail" a mail is correctly send (without changing any options). So, the error cannot result from spam protection of mail provider I'd say (all-inkl.com).
When restarting adapter it works some time until the error comes up again.

**To Reproduce**  
Just wait some time

**Expected behavior**  
Mails should always be sent

**Versions:**  
 - Adapter version: 1.1.3
 - Node version: v16.16.0
 - Operating system: Raspi OS (bullseye)

**Additional context**  
Was also occuring under Stretch and without compact mode.

**Comment by bryce2071** [comment]
same here. do you found a solution?

**Comment by Sneak-L8** [comment]
Unfortunately no. I installed WhatsApp adapter to be able to inform, if mail should break with that error. It works and since then, I got no further errors. Shure it'S not the solution, but it seems that this error comes and goes.
Perhaps some issue when having too less memory or problems with special characters or a codepage issue...

**Comment by Apollon77** [comment]
Hm ... any new insights? because why it should work some time and then not?

**Comment by Sneak-L8** [comment]
No new issues since August. Seems that error has disappeared

**Comment by Apollon77** [comment]
so close?

**Comment by Sneak-L8** [comment]
Yes, if it will occur again, we can reopen it
