### ISSUE TITLE
adapter.getMessage is deprecated and will be removed in js-controller 2.3

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.email#20]
Warning in Log for upcoming JS-Controller version 2.3 with hint: "Please report this warning to the developer of this adapter!"

**Comment by Apollon77** [comment]
Should be already fixed in 1.0.6 (latest repo). Can you please verify?

**Comment by Diginix** [comment]
Correct.
But I had to update manually to 1.0.6, even though I'm on latest channel. No hint for automatically update from 1.0.5.
