### ISSUE TITLE
adapter.getMessage is deprecated and will be removed in js-controller 2.3

### ISSUE THREAD

**Issue by Mic-M** [iobroker-community-adapters/ioBroker.email#21]
Warning message in log, with js-controller 2.2.7:

> email.0 | 2020-01-06 16:19:47.738 | warn | (27764) adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!

**Comment by Apollon77** [comment]
Please check 1.0.6

**Comment by Mic-M** [comment]
Thank you.
I am in latest repository, and adapter version 1.0.5 is the latest available, which I had installed. 
I've now updated manually through Github link in ioBroker admin, 1.0.6 was installed, and no longer the above mentioned warning in the log.
**Summary: resolved with version 1.0.6.**

**Comment by Apollon77** [comment]
I will make sure E-Mail 1.06 will be pushed later
