### ISSUE TITLE
warn | (793) adapter.getMessage is deprecated and will be removed in   js-controller 2.3.

### ISSUE THREAD

**Issue by Matdos** [iobroker-community-adapters/ioBroker.email#23]
Hay i have this warning in my log File, is it important? I should post it to the developer.

2020-02-01 17:29:19.803 | warn | (793) adapter.getMessage is deprecated and will be removed in   js-controller 2.3. Please report this warning to the developer of this   adapter!
-- | -- | --

Installed Version 1.0.5

Best regards.
Matdos

**Comment by Wildbill-Z** [comment]
Should be fixed in 1.06. Look her for [closed issue](https://github.com/iobroker-community-adapters/ioBroker.email/issues/20)
You have to manually update adapter in iobroker or change repo to latest.

**Comment by Matdos** [comment]
Hay, oh i have seen too late does an new Version available is, with the new 1.0.6 is it fix Thanks!!!
