### ISSUE TITLE
Cannot read property '__stopTimer'

### ISSUE THREAD

**Issue by frankLmn** [iobroker-community-adapters/ioBroker.email#24]
Hi,
I get these errors. I have already updated the adapter to 1.0.6 and have done all other updates.
Does anyone have an idea what I can do?

(2518) Error undefined
(2518)   uncaught exception: Cannot read property '__stopTimer' of undefined
(2518)   TypeError: Cannot read property '__stopTimer' of undefined at stop   (/opt/iobroker/node_modules/iobroker.email/main.js:52:17) at   transport.sendMail (/opt/iobroker/node_modules/iobroker.e
Caught   by controller[0]: TypeError: Cannot read property '__stopTimer' of undefined
Caught   by controller[0]: at stop   (/opt/iobroker/node_modules/iobroker.email/main.js:52:17)
Caught   by controller[0]: at transport.sendMail   (/opt/iobroker/node_modules/iobroker.email/main.js:188:9)
Caught   by controller[0]: at transporter.send.args   (/opt/iobroker/node_modules/nodemailer/lib/mailer/index.js:226:21)
Caught   by controller[0]: at SMTPConnection.connection.once.err   (/opt/iobroker/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
Caught   by controller[0]: at Object.onceWrapper (events.js:277:13)
Caught   by controller[0]: at SMTPConnection.emit (events.js:189:13)
Caught   by controller[0]: at SMTPConnection._onError   (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)
Caught   by controller[0]: at Immediate.setImmediate   (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:334:52)
Caught   by controller[0]: at runCallback (timers.js:705:18)
Caught   by controller[0]: at tryOnImmediate (timers.js:676:5)

**Comment by winampdevil** [comment]
It seems, that this error occur if the nameserver is not reachable or too slow.

I've seen this behavior, when the first resolver is invalid, error message "queryA EREFUSED [smtp-servername] .
The second resolver was ok, but too slow - or the email-adapter checks only the first.
