### ISSUE TITLE
Waiting to fix the email problem!

### ISSUE THREAD

**Issue by Sansibari** [iobroker-community-adapters/ioBroker.email#302]
**Describe the bug**  

Since September 2024, practically all email providers (hotmail/outlook, gmail, aol, yahoo .....) have blocked access with username & password.
What solutions/workarounds are there so that sending emails from ioBroker can be used or works again.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by mcm1957** [comment]
duplicate #261

**Comment by mcm1957** [comment]
The problem is registers with #261 and will be fixed whenever a developer has time to pick it up. Any PR to solve the problem is welcome.
 
For Questions / Diskussion please use the forum (https://forum.iobroker.net)
