### ISSUE TITLE
Error 451 4.3.0 pymilter: untrapped exception in pythonfilter

### ISSUE THREAD

**Issue by MC-1984** [iobroker-community-adapters/ioBroker.email#36]
With the latest version I get the following error message when I try to send a test email:

`Error 451 4.3.0 pymilter: untrapped exception in pythonfilter`

The log shows:

`
email.0 | 2020-06-30 14:46:33.765 | error | (27011) Error 451 4.3.0 pymilter: untrapped exception in pythonfilter
-- | -- | -- | --
`

Updating to the Github version did not resolve the error.

I am on js-controller 3.1.6 and nodejs 12.18. 

Any ideas?

**Comment by Apollon77** [comment]
When I google for it then the reason is the mail server that replies with this error ... so nothig where the adapter can do anything. Check the mail server please
