### ISSUE TITLE
local sendmail?

### ISSUE THREAD

**Issue by fungus75** [iobroker-community-adapters/ioBroker.email#6]
I tried to configure the local sendmail on a linux (debian) box:
Server: localhost
Port: 25
SSL: no (no mark)
Username: empty
Pass: empty

Got: wrong Certificate

Ok, now I could install let's encrypt,... but: I just want to use the local postfix. Isn't there any easy way of doing it?

**Comment by 150d** [comment]
I'm seeing the same problem: On pressing the "Test" button, the log says:

[code]
Error {"code":"ESOCKET","command":"CONN"}
[/code]

The mailserver is a local SMTP with no SSL and anonymous access.

Actually, I can't even imagine which certificate might be missing - by using no SSL, there shouldn't be any certificates by involved, should there?

I've read that a statement like

[code]
tls:{rejectUnauthorized:false}
or
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
[/code]

could fix the problem, but this would need to go into the adapter's source code, right?

**Comment by roadie33** [comment]
My e-mail instance is not working too. I'm using a local SMTP server without SSL. Authentification is not required. After pressing the "Test" Button got in the ioBroker logfile:
email.0 | 2019-12-08 18:19:43.999 | error | (8589) Error {"code":"EAUTH","command":"API"}
The logfile of my mailserver:
Dec  8 18:19:43 gateway postfix/smtpd[30226]: connect from iobroker[192.168.xxx.100]
Dec  8 18:19:44 gateway postfix/smtpd[30226]: lost connection after EHLO from iobroker[192.168.xxx.100]
Dec  8 18:19:44 gateway postfix/smtpd[30226]: disconnect from iobroker[192.168.xxx.100] ehlo=1 commands=1

**Comment by olifre** [comment]
I have the very same issue, with v1.0.10. 
Using the same settings:
```
Server: localhost
Port: 25
SSL: no (no mark)
Username: empty
Pass: empty
```
I get this in my Postfix log:
```
Aug 14 22:18:30 mynode postfix/smtpd[6949]: connect from localhost[127.0.0.1]
Aug 14 22:18:30 mynode postfix/smtpd[6949]: lost connection after STARTTLS from localhost[127.0.0.1]
Aug 14 22:18:30 mynode postfix/smtpd[6949]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=1 commands=2
```
And using the `Test` feature, I get in the adapter:
```
Error: self signed certificate
```
Is there any way to really disable SSL/TLS` 
I can confirm using `telnet` with port 25 on `localhost` works fine on the same machine.

**Comment by olifre** [comment]
Force-disabling any TLS in postfix can be used as a workaround:
```
smtpd_use_tls=no
```
