### ISSUE TITLE
Send Email SSL error

### ISSUE THREAD

**Issue by kuumaur** [iobroker-community-adapters/ioBroker.email#62]
Hi,
i try to send emails from iobroker via T-Online Mail Server.
(Already an open post at ioBroker Forum:
https://forum.iobroker.net/topic/40687/send-email-ssl-error/1)
When i do the SMTP server Test, i receive this error:
Error 139906210576256:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332

**To Reproduce**  
i assume, that the SMTP-Server securesmtp.t-online.de does not accept TLS 1.3.
openssl s_client -tls1_3 -starttls smtp securesmtp.t-online.de:587
CONNECTED(00000003)
140032464790656:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1544:SSL alert number 40

While openssl s_client -tls1_2 -starttls smtp securesmtp.t-online.de:587
is working properly.

**Expected behavior**  
Is there an option to enforce to use TLS 1.2?

**Versions:**  
 - Adapter version: 1.0.7
 - JS-Controller version: 3.1.6
 - Node version: v12.20.1
 - Operating system: Debian 10 x64 Proxmox LXC (uname -a: Linux fhem-prod 5.4.78-1-pve #1 SMP PVE 5.4.78-1 (Mon, 30 Nov 2020 10:57:47 +0100) x86_64 GNU/Linux)

**Additional context**

**Comment by kuumaur** [comment]
I took a 2nd try, now with Gmail.
If use my Gmail Account and selecting the predefined "GMail" entry, then the Adapter is working.
If i use the "user defined" entry and i fill in the values for GMail, then i receive the same error as for T-Online Servers.
To me it looks like an issue with the "User defined" function.

**Comment by kuumaur** [comment]
I have found an old post here:
https://forum.iobroker.net/topic/378/email-mit-web-de/8
It looks, that this issue is still valid.
As mentioned in the post, i created one GMail Account (instance 0) from the template and now i create a 2nd adapter (instance 1) with T-Online user defined and that worked for me.
That is my work around for now

**Comment by mule1972** [comment]
I am getting the same error when trying to use a Vodafone/Arcor account.

**Comment by mule1972** [comment]
Any chance this issue get fixed?

**Comment by Rooby69** [comment]
Hello I have the same issue with gmx email:

Fehler 3069745616:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Server:  mail.gmx.net 
Port: 587

**Comment by Apollon77** [comment]
Please try GitHub version, now a "always use STARTTLS" is set and some defaults to sslv3 are removed ...

**Comment by mamama1** [comment]
just edit /opt/iobroker/node_modules/iobroker.email/main.js and before line 160 (transport = require('nodemailer').createTransport(options); add the following line:
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

This kills all the stupid TLS/SSL crap which you don't need if you're on a LAN and UNAUTHENTICATED! Also, don't forget to untick the SSL checkbox in your instance configuration. WHY EVEN HAVE A CHECKBOX if it doesn't turn TLS/SSL properly OFF?

**Comment by Apollon77** [comment]
Hi @mamama1 you should fix your keyboard, Seems like Caps-key has issues.

And sorry biut this change proposal is not helpful beause it will turn this off foranything and always, so it might not be weanted. Your post is no answert o my question that the thread creator should check the GitHub version

**Comment by mamama1** [comment]
this issue is ongoing since the dinosaurs left the earth, I stopped trying and started fixing. for me, in this environment i don't give a sh*t about ssl verification of any means and everyone should consider for themselves whether this fix is valid for their environment or not. fact is, my setup is now again (finally!) working, after many useless proposals and non-working fixes which were published in the past in multiple places.

**Comment by Apollon77** [comment]
Then you can be happy and I can try to get feedback from users that care about official fixes and want to work together with us on fixing it.

**Comment by mamama1** [comment]
i will check back if it is fixed from my apartment on Mars! <3
