### ISSUE TITLE
Fehler unable to verify the first certificate

### ISSUE THREAD

**Issue by MirkoHuf** [iobroker-community-adapters/ioBroker.email#66]
**Describe the bug**  
I have a Synology NAS with a local eMail service. Fritzbox and HP printer are using this SMTP since months now without any problems. Now i try to establish a connection to my iobroker instance. But i get errors:

SMTP port 25: Fehler unable to verify the first certificate
port 465: Fehler unable to verify the first certificate
port 586; Fehler 140674551363456:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

I don't need a SSL transaction because it's local - but also on port 25 without "ssl" I got an "unable to verify the first certificate" error.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/7764831/104967963-eb4c6500-59e4-11eb-9dd6-ee363483c750.png)

**Versions:**  
 - Adapter version: 1.0.7

**Comment by meinpilsbier** [comment]
We need an additional option for user defined service.
ignoreTLS

**Comment by mamama1** [comment]
where on earth is this fixed, why does this adapter force us to use valid tls if we are only using local, non-public mail servers, jesus christ, how can this be so difficult to implement!

**Comment by Apollon77** [comment]
@mamama1 Please caref7lly think about your words and language.

It is fixed on GitHub and yes I forgot to post here the question to check out GitHub version

**Comment by mamama1** [comment]
F bomb dropping

**Comment by danielhainich** [comment]
Hi, I have installer the New Version, but iam not able to sent an Email with custom settings. I also want to use synology Email Server plain on tcp/25. It doesnt work with or without auth. Same error with first cert.

**Comment by Apollon77** [comment]
which settings you choose? tcp/25 should not have any cert ... encrypted is other ports, so enabling ssl with port 25 makes no sense

**Comment by mamama1** [comment]
> which settings you choose? tcp/25 should not have any cert ... encrypted is other ports, so enabling ssl with port 25 makes no sense

LOL are you serious? that's literally the issue people all over the internet have been complaining about for years. that stupid email adapter stubbornly tries to do TLS, no matter what settings or ports you use. i bet my bottom dollar that @danielhainich had SSL disabled and port 25 selected.

**Comment by Apollon77** [comment]
@mamama1 beside your completely unneeded wording again it is new to me, so ... so maybe then we have a point to fix it ... if this can be proofed

**Comment by danielhainich** [comment]
> which settings you choose? tcp/25 should not have any cert ... encrypted is other ports, so enabling ssl with port 25 makes no sense

Hi, as I wrote - plain, not encrypted on Port 25. But there raises an error that the first cert cannot be verified. There is no cert. I Set the Adapter to debug, but there is debug output within the logs. Where I have to Look for more Details according this error?

**Comment by Apollon77** [comment]
Please try GitHub version.

The issue was in the details of the used nodemailer library:
> If false (the default) then TLS is used if server supports the STARTTLS extension.

So it seems that the server even on port 25 announced support and so it was used.

With the new version TLS should be completelxy ignored when disabling ssl in settings

**Comment by danielhainich** [comment]
For me it's working right now. Thanks.

**Comment by Apollon77** [comment]
Ok, then I will release a new version. Thank you for your support

**Comment by mamama1** [comment]
> So it seems that the server even on port 25 announced support and so it was used.

That is literally the purpose of STARTTLS, to start TLS on ports where TLS is not implicitly used:
https://datatracker.ietf.org/doc/html/rfc3207
https://datatracker.ietf.org/doc/html/rfc8314

#justsaying

**Comment by Apollon77** [comment]
But then the new setting since last version (not contained in screenshot above) to ignore ssl cert errors should have been enough already?!

**Comment by mamama1** [comment]
probably. I don't know about that since I'm running v1.0.10 and haven't looked back since I have nuked the broken TLS stuff completely with "process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";"

But I kinda doubt that @danielhainich didn't try the setting to ignore ssl cert errors.
