### ISSUE TITLE
callback function is never called

### ISSUE THREAD

**Issue by arniworx** [iobroker-community-adapters/ioBroker.email#68]
**Describe the bug**  
`sendTo('email.0', 'send', {to: "info@test.de", subject: "test", body: "testbody" }, function(res) { /* handle res here */ }); 
`
the callback function is not called by the adapter (not called at all)

**To Reproduce**  
just exec the above 

**Expected behavior**  
handle error or success in the callback function

**Screenshots & Logfiles**  
none

**Versions:**  
 - Adapter version: 1.0.7
 - JS-Controller version: 3.2.16
 - Node version: 12.20.1
 - Operating system: ubuntu 18.04.5 LTS

**Additional context**  
none

**Comment by Apollon77** [comment]
Righ now this is kind of expected because the code only calls the callbacl in ne case on error ... we could adjust that

**Comment by Apollon77** [comment]
please try github version (version number is the same). working that way?

**Comment by arniworx** [comment]
yes, it works. thank you.
why don't you return just 'null' instead of {'error': null} on success?
anyway, just cosmetic
